### ISSUE TITLE
[feature]: Add Redis support for Java SDK

### ISSUE THREAD

**Issue by charankamarapu** [keploy/java-sdk#118]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Java SDK does not have Redis support, so Redis Database cannot be mocked . This support needs to be added as many projects use Redis as a Database.

### Why should this be worked on?

Adding support to various Databases will improve Keploy's mocking feature .

**Comment by gouravkrosx** [comment]
Closes with https://github.com/keploy/java-sdk/pull/119
