### ISSUE TITLE
[feature]: Conditional mocking of dependencies

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/java-sdk#124]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

This feature enables conditional mocking of dependencies. Specifically, I have multiple dependencies that need to be mocked, but I would like the ability to selectively exclude certain dependencies from being mocked based on user input. 

For example, if a user specifies that a particular dependency should not be mocked, only that specific dependency will be excluded from mocking while the others will still be mocked.

"One way to implement this feature could be by introducing a new flag or environmental variable that controls whether or not a particular dependency should be mocked. Users could set this flag to 'true' or 'false' depending on their needs, and the mocking behavior would be adjusted accordingly."

### Why should this be worked on?

This would be extremely helpful for managing dependencies in complex projects with many interdependent modules.

**Comment by reem-atalah** [comment]
I want to be assigned to this issue
