### ISSUE TITLE
[feature]: Add sonarlint code styling guidelines

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [keploy/java-sdk#139]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Sonarlint is a linting extension for VS-Code, VS and other IDEs which provides guidelines on how the Java code should be structured and what are the best practices to be followed based on [https://rules.sonarsource.com/java](https://rules.sonarsource.com/java). 

### Why should this be worked on?

Adding the styling guide and sticking to the best practices would help in faster adoption of the Hava SDK in enterprise architecture. Also it saves the SDK from bugs.

**Comment by Sarthak160** [comment]
This has been done under #129
