### ISSUE TITLE
[feature]: Add CLI build, lint and test options

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [keploy/java-sdk#140]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

CLI-based build, lint and test is a good and easy way to ensure that the code being pushed doesn't suffer from trivial issues.

### Why should this be worked on?

This would help SDK developers to test what changes they are making with minimal risks of introducing breaking changes to the SDK.

**Comment by Sarthak160** [comment]
This is covered under #133
