### ISSUE TITLE
[feature]: Add coverage based tests

### ISSUE THREAD

**Issue by ArkaprabhaChakraborty** [keploy/java-sdk#141]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

Coverage-based testing is a great way to ensure that the changes being introduced get tested thoroughly. A minimum code coverage score should be maintained before merging any feature. [Codecov](https://about.codecov.io/) is a great way to do this.

### Why should this be worked on?

This ensures that the SDK/product doesn't go through any unsolicited changes or doesn't have any odd arbitrary lines which can be later leveraged by a vulnerability. Coverage guiding tests also help in developing rock-solid SDKs with the core idea that every sections gets tested.

**Comment by Sarthak160** [comment]
This issue can be covered under #131
