### ISSUE TITLE
[feature]: automatically set test mode during junit tests

### ISSUE THREAD

**Issue by slayerjain** [keploy/java-sdk#26]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

We must set the `KEPLOY_MODE = test` even before running JUnit tests. This should be automatically inferred. 

### Why should this be worked on?

Improves users experiences by reducing redundant config.

**Comment by gouravkrosx** [comment]
closes with https://github.com/keploy/samples-java/pull/9
