### ISSUE TITLE
[bug]: test suite stop if application stops

### ISSUE THREAD

**Issue by slayerjain** [keploy/java-sdk#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Testing stops with the application (system under test) if it crashes. 

### Steps to reproduce

1. Record tests (some should make app crash)
2. Run test suites
3. Tests after the crashes aren't executed

### Environment

Deploy preview

### Version

Local

**Comment by gouravkrosx** [comment]
closes by PR: (https://github.com/keploy/java-sdk/pull/31)
