### ISSUE TITLE
[feature]: Add support for mocking database queries in java sdk

### ISSUE THREAD

**Issue by Sarthak160** [keploy/java-sdk#29]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Should add integration for mocking SQL/JDBC methods by creating a custom driver . 
- Driver class should act as wrapper around `java.sql.Driver` and other sql interfaces.
- It should be compatible with any ORM like JPA and Hibernate .
- Classes should be load at runtime and integration with client should be smooth .
- Should be generic for all sql compliance databases like postgres , MySql , SQLite etc.
- Good to have - It should be interacting with API explicitly as it will be easier to use for people who don't have to change the code bases like QA (Can use Java Agents and  [ByteBuddy]( https://bytebuddy.net/#/tutorial)) for that

### Why should this be worked on?

By this We will be able to mock the database queries during recording testcases and will be able to replicate them during test run . 
This will help user to record replay API tests without writing their stubbs / mocks

**Comment by gouravkrosx** [comment]
closes with above PR
