### ISSUE TITLE
[bug]: Improper logs if failure at keploy

### ISSUE THREAD

**Issue by slayerjain** [keploy/java-sdk#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If there are any errors in keploy, eg: keploy is not able to read the yaml. The SDK just creates null pointer exception. 

### Steps to reproduce

1. Install keploy
2. Install Java SDK in the app
3. use an incorrect schema in the test files. 
4. Null pointer exception in java sdk. 

### Version

Local

**Comment by re-Tick** [comment]
closes with https://github.com/keploy/keploy/pull/178.
