### ISSUE TITLE
[feature]: add support for OkHttpClient dependency mocking.

### ISSUE THREAD

**Issue by gouravkrosx** [keploy/java-sdk#51]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Should add integration for mocking **OkHttpClient** dependency.
- Good to have - It should be interacting with API explicitly as it will be easier to use for people who don't have to change the code bases like QA (Can use Java Agents and [ByteBuddy](https://bytebuddy.net/#/tutorial)) for that.

### Why should this be worked on?

By this, We will be able to mock the **OkHttpClient's** HTTP requests when recording test cases and will be able to replicate them during the test run.
This will help users record replay API tests without writing their stubs/mocks.

**Comment by Sarthak160** [comment]
Is this still open  @gouravkrosx  ?

**Comment by gouravkrosx** [comment]
No, you can close this.
