### ISSUE TITLE
[feature]:  add interceptors for mocking http client calls in API

### ISSUE THREAD

**Issue by Sarthak160** [keploy/java-sdk#71]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Since keploy generates mocks along with testcases to mock infra structure calls like http client calls , db calls , message queues , it's necessary to add integrations for **dependency mocking** .

- As http clients are the most commonly used external dependencies which help an API to perform and communicate to other services as well as APIs . We can add interceptors which can act as an intermediate between the `http requests` and `response` .

- We can save the all the attributes of that call in `HTTP SPEC` in the form of yamls.
- We can replay those at test mode and this time we would be using mocks rather than making actual api calls to the external servers .
- We can implement this feature for [Apache](https://javadoc.io/doc/org.apache.httpcomponents/httpclient/latest/index.html) and [Okhttp](https://javadoc.io/doc/com.squareup.okhttp3/okhttp/3.3.1/okhttp3/OkHttpClient.html) clients which are widely used in java applications .
- Integration can be smooth if user will be able to integrate in its application on the fly . For that we can use some ASM library tools like _**[Bytebuddy](https://bytebuddy.net/#/)**_ .
- Then user can define the agent JAR in its VM options of IDE or run manually using cli command .

### Why should this be worked on?

This is an important feature to showcase the mocking infra capabilities of **_[keploy](https://keploy.io/)_**
Also user will be able to test its API with ETE tests generated by keploy without caring about test environments
Tests and mocks generated will be more realistic are captured from the real traffic .

**Comment by gouravkrosx** [comment]
Closes with the above PR #73
