### ISSUE TITLE
[feature]:  Add support for mocking infra calls of dynamoDb aws sdk

### ISSUE THREAD

**Issue by Sarthak160** [keploy/java-sdk#72]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Summary

- Since AWS Dynamo db internally uses apache client for making transactional calls .
- I will nice if we can intercept those calls and replay them at the time of test mode 
- Making this thing work will help us to mock dynamo db and store it's mock in the form of yamls

### Why should this be worked on?

This is an important feature to showcase the mocking infra capabilities of **_[keploy](https://keploy.io/)_**
Also user will be able to test its API with ETE tests generated by keploy without caring about test environments
Tests and mocks generated will be more realistic are captured from the real traffic .

**Comment by gouravkrosx** [comment]
Since dynamoDb internally uses apache HTTP client and now java-sdk supports the mocking feature of the same. Hence closing this issue with PR #73
